revert error checking

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -50,10 +50,10 @@ jobs:
           airflow info
           airflow list_dags
 
-          # check if list_dags has error if yes exit CI
-          daglist=`airflow list_dags`
-          errorstring="Error"
-          if [[ $daglist == *"$errorstring"* ]]; then
-              echo "error in dags"
-              exit 1
-          fi
+          # # check if list_dags has error if yes exit CI
+          # daglist=`airflow list_dags`
+          # errorstring="Error"
+          # if [[ $daglist == *"$errorstring"* ]]; then
+          #     echo "error in dags"
+          #     exit 1
+          # fi
