add db init check

diff --git a/.github/workflows/v2_check.yaml b/.github/workflows/v2_check.yaml
--- a/.github/workflows/v2_check.yaml
+++ b/.github/workflows/v2_check.yaml
@@ -60,12 +60,21 @@ jobs:
           export AIRFLOW__CORE__DAGS_FOLDER="/home/runner/work/dea-airflow/dea-airflow/dags"
 
           airflow db init
+
+          # check if db init has error if yes exit CI
+          dbinit=`airflow db init`
+          errorstring="Error"
+          if [[ $dbinit == *"$errorstring"* ]]; then
+              echo "error in db init"
+              exit 1
+          fi
+
           airflow connections add 'aws_nci_db_backup' --conn-type 'aws' --conn-login 'AWSKEY' --conn-password 'AWS_PASS'
           airflow connections add 'lpgs_gadi' --conn-type 'ssh' --conn-login 'USERNAME' --conn-password 'PASS'
           airflow info
           airflow dags list
 
-          # check if list_dags has error if yes exit CI
+          # check if dags list has error if yes exit CI
           daglist=`airflow dags list`
           errorstring="Error"
           if [[ $daglist == *"$errorstring"* ]]; then
