add test

diff --git a/.github/workflows/v2_check.yaml b/.github/workflows/v2_check.yaml
--- a/.github/workflows/v2_check.yaml
+++ b/.github/workflows/v2_check.yaml
@@ -1,5 +1,5 @@
 ---
-name: DAGs unit tests
+name: v2.1 DAGs unit tests
 
 on:
   push:
@@ -33,7 +33,8 @@ jobs:
     strategy:
       matrix:
         python-version: [3.8]
-    name: Airflow ${{ matrix.python-version }}
+        airflow-version: [2.1.0]
+    name: Airflow ${{ matrix.airflow-version }}
     steps:
       - uses: actions/checkout@v2
       - name: Install Airflow and Lint
@@ -48,10 +49,10 @@ jobs:
         run: which python
       - name: Install airflow and run pylint
         run: |
-          pip install apache-airflow[aws,kubernetes,postgres,redis,ssh,celery]==2.1.0 -c constraints.txt --upgrade
-          pip install pylint pylint-airflow
+          pip install apache-airflow[aws,kubernetes,postgres,redis,ssh,celery]==${{ matrix.airflow-version }} -c constraints.txt
+          # pip install pylint pylint-airflow
           pip install -r requirements.txt
-          pylint --load-plugins=pylint_airflow --disable=C,W --disable=similarities dags
+          # pylint --load-plugins=pylint_airflow --disable=C,W --disable=similarities dags
       - name: setup airflow and check dags list
         run: |
           export AIRFLOW__CORE__LOAD_EXAMPLES="False"
@@ -59,6 +60,18 @@ jobs:
           export AIRFLOW__CORE__DAGS_FOLDER="/home/runner/work/dea-airflow/dea-airflow/dags"
 
           airflow db init
+          airflow connections --add --conn_id aws_nci_db_backup --conn_type aws --conn_login AWSKEY --conn_password AWS_PASS
+          airflow connections --add --conn_id lpgs_gadi --conn_type ssh --conn_login USERNAME --conn_password PASS
+          airflow info
+          airflow dags list
+
+          # check if list_dags has error if yes exit CI
+          daglist=`airflow dags list`
+          errorstring="Error"
+          if [[ $daglist == *"$errorstring"* ]]; then
+              echo "error in dags"
+              exit 1
+          fi
 
       - name: run tests on dags
         run: |
