update test

diff --git a/.github/workflows/v2_check.yaml b/.github/workflows/v2_check.yaml
--- a/.github/workflows/v2_check.yaml
+++ b/.github/workflows/v2_check.yaml
@@ -36,7 +36,10 @@ jobs:
         airflow-version: [2.1.2]
     name: Airflow ${{ matrix.airflow-version }}
     steps:
-      - uses: actions/checkout@v2
+      - name: checkout git
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
       - name: Install Airflow and Lint
         uses: s-weigand/setup-conda@v1
         with:
@@ -55,28 +58,28 @@ jobs:
           pylint --load-plugins=pylint_airflow --disable=C,W --disable=similarities dags
       - name: setup airflow and check dags list
         run: |
+          airflow db upgrade
+          airflow db init
+
           export AIRFLOW__CORE__LOAD_EXAMPLES="False"
           export AIRFLOW__CORE__PLUGINS_FOLDER="/home/runner/work/dea-airflow/dea-airflow/plugins"
           export AIRFLOW__CORE__DAGS_FOLDER="/home/runner/work/dea-airflow/dea-airflow/dags"
 
-          airflow version
-          echo "y" | airflow db reset
-          airflow db init
           airflow connections add 'aws_nci_db_backup' --conn-type 'aws' --conn-login 'AWSKEY' --conn-password 'AWS_PASS'
           airflow connections add 'lpgs_gadi' --conn-type 'ssh' --conn-login 'USERNAME' --conn-password 'PASS'
           airflow info
-          airflow dags list
+          airflow dags list -v
 
-          # check if dags list has error if yes exit CI
-          daglist=`airflow dags list`
-          errorstring="Error"
-          if [[ $daglist == *"$errorstring"* ]]; then
-              echo "error in dags"
-              exit 1
+          # check if list_dags has error if yes exit CI
+          airflow dags list -v > dag_list.txt
+          if grep -rniw './dag_list.txt' -e 'Error'; then
+            echo "error found"
+            exit 1
           fi
 
       - name: run tests on dags
         run: |
+          # export AIRFLOW__CORE__UNIT_TEST_MODE="True"
           export PYTHONPATH="${PYTHONPATH:+${PYTHONPATH}:}${PWD}/dags"
           pip install pylint==2.7.2 pytest==6.2.2 pylint-airflow
           pytest tests/dag_structure
